checks:
  php:
    code_rating: true
    duplication: true

build:
  environment:
    php: 7.4.3
  nodes:
    coverage:
      tests:
        override:
          - command: 'XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text'
            coverage:
              file: 'build/coverage/log/coverage.xml'
              format: 'clover'
          - phpcs-run --ignore=*/tests/*

filter:
  excluded_paths:
    - "tests/"
