build:
  environment:
    php: 7.4.3
  nodes:
    coverage:
      tests:
        override:
          - command: 'XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text'
            coverage:
              file: 'build/coverage/log/coverage.xml'
              format: 'clover'
          - phpcs-run
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  paths:
    - src/
  excluded_paths:
    - tests/
  dependency_paths:
    - vendor/
